using System;

namespace NDceRpc.Microsoft.Interop
{
	[Flags]
	public enum RPC_CALL_ATTRIBUTES_FLAGS
	{
		RPC_QUERY_SERVER_PRINCIPAL_NAME = 0x2,
		RPC_QUERY_CLIENT_PRINCIPAL_NAME = 0x4,
		RPC_QUERY_CALL_LOCAL_ADDRESS = 0x8,
		RPC_QUERY_CLIENT_PID = 0x10,
		RPC_QUERY_IS_CLIENT_LOCAL = 0x20,
		RPC_QUERY_NO_AUTH_REQUIRED = 0x40
	}
}
